services:

  # PostgreSQL database
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fakedb
    volumes:
      - ./fakedb:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  
  # pgadmin: GUI for PostgreSQL database
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

  # Generator 
  pydatagen:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-python-app
    working_dir: /app
    volumes:
      - ./pyfakedata:/data
    command: python src/generate_fake_data.py